---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: longan-web-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/pv/longan/app-web"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: longan
  name: longan-web-pvc
  labels:
    app: longan-web
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: longan-web-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: longan-db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/pv/longan/app-db"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: longan
  name: longan-db-pvc
  labels:
    app: longan-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: longan-db-pv